apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
  - name: "result-service-port"
    port: 8080
    targetPort: 80
    nodePort: 32000
  selector:
    app: result

